### ISSUE TITLE
Passing assets directly as an input of the component

### ISSUE THREAD

**Issue by bornegui** [bkrem/react-nft-gallery#4]
The issue with making the API calls on the client side is that when an API key is used it'll be visible in the Network tabs and so anyone could steal it.

<img width="192" alt="Screenshot 2022-02-13 at 14 14 39" src="https://user-images.githubusercontent.com/1843503/153760316-41d61410-f5f5-4fbb-9b9e-cb6f73249597.png">

In an ideal world, the API calls would be made on the server side and we could pass the assets to your component which would render them.

So would be awesome if you could add this feature!!

**Comment by bkrem** [comment]
Resolved via #5 and #6, closing.
