### ISSUE TITLE
Fixes for Opensea API changes

### ISSUE THREAD

**Issue by trkaplan** [bkrem/react-nft-gallery#6]
I've sent a PR ( https://github.com/bkrem/react-nft-gallery/pull/5 ) related to Opensea API. Plus Auto-retry and Retry Button features. 

![ss-opensea-api-fix-retry-button](https://user-images.githubusercontent.com/992897/161293583-417f3965-9e1b-4956-9a45-ab39eb09ba9f.png) 

![ss-opensea-api-fix-new-props](https://user-images.githubusercontent.com/992897/161293592-fa87613e-6145-42ef-b6c5-70af297454a4.png)

**Comment by bkrem** [comment]
Published the changes in #5 as https://github.com/bkrem/react-nft-gallery/releases/tag/v0.7.0

I squash-merged our combined commits into `main`, but you can see the remaining changes I made on this branch: https://github.com/bkrem/react-nft-gallery/tree/feat/custom-api-support

If you notice any bugs or other regressions please let me know of course.

Thanks again for your awesome work here :) 🙏

**Comment by trkaplan** [comment]
Awesome! I'll inform you when I add a restriction to use the proxy API. Like  I said It is normally for private use :)

**Comment by bkrem** [comment]
> Awesome! I'll inform you when I add a restriction to use the proxy API. Like I said It is normally for private use :)

Of course, don’t want to blow up your proxy via exposure here, thanks for providing it to get this feature shipped 💪 
That would be great if you give me a heads up, then I can adjust the storybook with a replacement 👍
